### ISSUE TITLE
problem with disablecf

### ISSUE THREAD

**Issue by LiftedKilt** [danielpigott/cloudflare-cli#10]
when I run "cfcli disablecf [record]", I receive the following record. I have tested it on multiple records.

/usr/lib/node_modules/cloudflare-cli/lib/cli.js:222
    var matches = cfcli.findRecord(name, false, result);
                        ^
TypeError: Object #<CloudflareCli> has no method 'findRecord'
    at editRecord (/usr/lib/node_modules/cloudflare-cli/lib/cli.js:222:25)
    at /usr/lib/node_modules/cloudflare-cli/node_modules/cloudflare/lib/cloudflare.js:123:7
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/cloudflare-cli/node_modules/cloudflare/lib/cloudflare.js:652:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by danielpigott** [comment]
Thanks @LiftedKilt  I have merged in your pull request and published the fix to npm
