### ISSUE TITLE
invalid zone

### ISSUE THREAD

**Issue by maelsaiedy** [danielpigott/cloudflare-cli#19]
Hello, 

Is it updated for v4 of the API

I get this error when trying to purgefile

Error: Invalid zone
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloudflare-cli/node_modules/cloudflare/lib/cloudflare.js:654:10)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by danielpigott** [comment]
Hi,
I am still using an older version of the api.  I am looking to update cfcli to use the newer api using this library https://www.npmjs.com/package/cloudflare.
This will happen with version 2, which will be a rewrite for the most part.

**Comment by danielpigott** [comment]
cloudflare-cli v2 now uses the v4 api.
