### ISSUE TITLE
Tabs in config

### ISSUE THREAD

**Issue by staff0rd** [danielpigott/cloudflare-cli#20]
Using tabs in .cfcli.yml breaks;

~~~
C:\Users\stafford\AppData\Roaming\npm\node_modules\cloudflare-cli\lib\argv.js:50
            if(ymlConfig.defaults.account || argv.account) {
                                 ^

TypeError: Cannot read property 'account' of null
    at Object.exports.run (C:\Users\stafford\AppData\Roaming\npm\node_modules\cloudflare-cli\lib\argv.js:50:34)
    at new CloudflareCli (C:\Users\stafford\AppData\Roaming\npm\node_modules\cloudflare-cli\lib\cli.js:9:15)
    at Object.module.exports.createCli (C:\Users\stafford\AppData\Roaming\npm\node_modules\cloudflare-cli\lib\cli.js:352:12)
    at Object.<anonymous> (C:\Users\stafford\AppData\Roaming\npm\node_modules\cloudflare-cli\bin\cfcli:2:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
~~~

Note i'm using the default config, not the accounts config.

**Comment by danielpigott** [comment]
The config file is yaml which doesn't support tabs for indentation (http://www.yaml.org/spec/1.2/spec.html#id2777534)
That said, I will look at adding a sensible error if parsing of the config file fails

**Comment by danielpigott** [comment]
Added check to fail if unable to read config file in v2
